version: '3.8'

services:
  backend:
    build: ./currency
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/h2db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "5500:80"
    depends_on:
      - backend